#!/usr/bin/env python3
"""Case table for the `worktree-hygiene` skill's session_map.py.

Every case here is a bug that shipped in a draft of that script and produced
plausible-but-wrong output rather than an error — the failure mode that makes a
session-mapping tool worse than no tool, because its answers look like facts.

Run directly, or via `make lint`.
"""

from __future__ import annotations

import importlib.util
import json
import pathlib
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[2]
SCRIPT = ROOT / ".claude/skills/worktree-hygiene/scripts/session_map.py"

spec = importlib.util.spec_from_file_location("session_map", SCRIPT)
sm = importlib.util.module_from_spec(spec)
spec.loader.exec_module(sm)

failures: list[str] = []


def check(name: str, got: object, want: object) -> None:
    if got == want:
        print(f"  ok   {name}")
    else:
        print(f"  FAIL {name}\n         got:  {got!r}\n         want: {want!r}")
        failures.append(name)


def write_session(directory: pathlib.Path, sid: str, records: list[dict]) -> pathlib.Path:
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{sid}.jsonl"
    path.write_text("".join(json.dumps(r) + "\n" for r in records))
    return path


def user(text: object, when: str = "2026-01-01T00:00:00Z") -> dict:
    return {"type": "user", "timestamp": when, "message": {"content": text}}


with tempfile.TemporaryDirectory() as tmp:
    tmpdir = pathlib.Path(tmp)
    sid = "11111111-1111-1111-1111-111111111111"

    # --- the shape of a user message -------------------------------------------------
    # Nearly every user record stores content as a list of typed blocks. A draft accepted
    # only a plain string, so the first-message fallback was dead for ~99% of sessions and
    # every one of them was reported as "(untitled)" — silently, as if it had no name.
    blocks = write_session(tmpdir / "blocks", sid, [user([{"type": "text", "text": "пробуй"}])])
    check("list-shaped content yields the first message", sm.Session(blocks).title, "пробуй")

    plain = write_session(tmpdir / "plain", sid, [user("a typed prompt")])
    check("string-shaped content still works", sm.Session(plain).title, "a typed prompt")

    check("a non-text block is skipped, not stringified",
          sm._text_of([{"type": "image", "source": {}}, {"type": "text", "text": "after"}]),
          "after")

    # --- what is not a prompt ---------------------------------------------------------
    recap = write_session(tmpdir / "recap", sid, [
        user([{"type": "text", "text": "This session is being continued from a previous run"}]),
        user([{"type": "text", "text": "the real first question"}]),
    ])
    check("a resume recap is not taken as the title",
          sm.Session(recap).title, "the real first question")

    caveat = write_session(tmpdir / "caveat", sid, [
        user("Caveat: The messages below were generated by the user while running local commands"),
        user([{"type": "text", "text": "what a person actually asked"}]),
    ])
    check("a local-command caveat is not taken as the title",
          sm.Session(caveat).title, "what a person actually asked")

    # --- title priority ----------------------------------------------------------------
    ranked = write_session(tmpdir / "ranked", sid, [
        user([{"type": "text", "text": "typed first"}]),
        {"type": "ai-title", "aiTitle": "generated"},
        {"type": "custom-title", "customTitle": "chosen by a person"},
    ])
    check("a person's name outranks the generated one",
          sm.Session(ranked).title, "chosen by a person")
    check("the generated name is read from aiTitle, not title",
          sm.Session(write_session(tmpdir / "ai", sid,
                                   [{"type": "ai-title", "aiTitle": "generated"}])).title,
          "generated")

    # --- merging two files of one session ----------------------------------------------
    # Renaming a session writes a custom-title stub in the directory it is renamed from,
    # while the transcript stays where the work happened. A draft merged them by which file
    # was read first — and since a repository's root project directory always sorts before
    # its worktree directories, that discarded the human's rename every time.
    stub = sm.Session(write_session(tmpdir / "split-root", sid,
                                    [{"type": "custom-title", "customTitle": "the human name"}]))
    full = sm.Session(write_session(tmpdir / "split-wt", sid, [
        {"type": "ai-title", "aiTitle": "a stale generated name"},
        {"type": "user", "timestamp": "2026-05-05T10:00:00Z", "cwd": "/late",
         "gitBranch": "task/late", "message": {"content": "x"}},
    ]))

    a, b = sm.Session(stub.path), sm.Session(full.path)
    a.absorb(b)
    b2, a2 = sm.Session(full.path), sm.Session(stub.path)
    b2.absorb(a2)
    check("the human name survives when the stub is read first", a.title, "the human name")
    check("the human name survives when the stub is read second", b2.title, "the human name")

    early = sm.Session(write_session(tmpdir / "early", sid, [
        {"type": "user", "timestamp": "2026-01-01T10:00:00Z", "cwd": "/early",
         "gitBranch": "task/early", "message": {"content": "x"}}]))
    late = sm.Session(full.path)
    early.absorb(late)
    check("the later directory wins the merge, not the later file", early.last_cwd, "/late")
    check("the later branch wins the merge, not the later file",
          early.last_branch, "task/late")

    # --- which project directories belong to this repository ---------------------------
    # A bare prefix match folds a sibling project's sessions into the report with no error.
    projects = tmpdir / "projects"
    for name in ("-repo-Sample", "-repo-Sample--claude-worktrees-task-a", "-repo-Sample2"):
        (projects / name).mkdir(parents=True)
    sm.PROJECTS = str(projects)
    found = {pathlib.Path(d).name for d in sm.project_dirs("/repo/Sample")}
    check("a sibling project whose name extends this one is excluded",
          found, {"-repo-Sample", "-repo-Sample--claude-worktrees-task-a"})

print()
if failures:
    print(f"[verify-session-map] FAILED: {len(failures)} case(s): {', '.join(failures)}")
    sys.exit(1)
print("[verify-session-map] OK: all cases hold.")
